# Generated by Django 4.2.14 on 2024-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=255)),
                ('review_content', models.TextField()),
                ('review_score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('display_name', models.CharField(default='Titan Kwishalikwa', max_length=100)),
            ],
        ),
    ]
