# Generated by Django 4.2.14 on 2024-09-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Afri Fund', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='press.leadership')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('author', models.CharField(default='Afri Fund', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='press.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='unique_title_per_category'),
        ),
    ]
