# Generated by Django 4.2.14 on 2024-09-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('author', models.CharField(default='Afri Fund', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='press.category')),
            ],
        ),
    ]
