# Generated by Django 4.2.14 on 2024-09-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.URLField(),
        ),
    ]
