# Generated by Django 4.2.14 on 2024-09-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_category_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
