# Generated by Django 4.2.14 on 2024-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_alter_leadership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.URLField(default='https://cdn.collegeavestudentloans.com/ca2023/wp-content/uploads/2023/10/07145727/joe-depaulo.png', max_length=400),
        ),
    ]
