# Generated by Django 4.2.14 on 2024-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_alter_leadership_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Refinance', 'Refinance'), ('StudentLoan', 'Student Loan'), ('ParentLoan', 'Parent Loan'), ('CareerLoan', 'Career Loan'), ('StudentCard', 'Student Card')], default='StudentLoan', max_length=255)),
                ('content', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Footnotes',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='footnote',
            constraint=models.UniqueConstraint(fields=('category', 'content'), name='unique_category_and_content'),
        ),
    ]
