# Generated by Django 4.2.14 on 2024-10-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_footnote_footnote_unique_category_and_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='category',
            field=models.CharField(choices=[('Refinance', 'Refinance'), ('StudentLoan', 'Student Loan'), ('ParentLoan', 'Parent Loan'), ('CareerLoan', 'Career Loan'), ('StudentCard', 'Student Card'), ('Calculator', 'Calculator'), ('Custom', 'Custom')], default='Custom', max_length=255),
        ),
    ]
