# Generated by Django 4.2.14 on 2024-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
    ]
