# Generated by Django 4.2.14 on 2024-09-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_number',
        ),
    ]
