# Generated by Django 4.2.14 on 2024-09-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city_town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=100)),
                ('national_id_confirmation', models.CharField(blank=True, max_length=100)),
                ('high_school_attended', models.CharField(max_length=100)),
                ('mean_grade_attained', models.CharField(blank=True, max_length=100)),
                ('college_university_admitted', models.CharField(choices=[('JKUAT', 'Jomo Kenyatta University of Agriculture and Technology'), ('KU', 'Kenyatta University'), ('UON', 'University of Nairobi'), ('MASENO', 'Maseno University')], default='JKUAT', max_length=100)),
                ('course_admitted', models.CharField(choices=[('BACHELOR_OF_SCIENCE_IN_AGRICULTURE', 'Bachelor of Science in Agriculture'), ('BACHELOR_OF_SCIENCE_IN_TECHNOLOGY', 'Bachelor of Science in Technology'), ('BACHELOR_OF_ARTS_AND_HUMAN_SOCIETY', 'Bachelor of Arts and Human Societies'), ('BACHELOR_OF_ENGINEERING', 'Bachelor of Engineering'), ('BACHELOR_OF_MATHEMATICS_AND_STATISTICS', 'Bachelor of Mathematics and Statistics'), ('MASTER_OF_ARTS_IN_AGRICULTURAL_AND_HUMAN_SOCIETY', 'Master of Arts in Agricultural and Human Societies'), ('BACHELOR_OF_COMPUTER_SCIENCE', 'Bachelor of Computer Science'), ('BACHELOR_OF_LAW', 'Bachelor of Law')], default='BACHELOR_OF_LAW', max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('national_id_scanned_copy', models.ImageField(blank=True, upload_to='applications/')),
                ('high_school_certificate_scanned_copy', models.ImageField(blank=True, upload_to='applications/')),
                ('college_university_admitted_scanned_copy', models.ImageField(blank=True, upload_to='applications/')),
                ('serial_number', models.CharField(blank=True, max_length=1000)),
                ('serial_id', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='applications.loanapplication')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_category', to='applications.loancategory'),
        ),
    ]
