# Generated by Django 4.2.14 on 2024-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_loanapplication_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='county',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='home_county',
            field=models.CharField(choices=[], default='MIGORI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='residence_county',
            field=models.CharField(choices=[], default='MIGORI', max_length=100),
            preserve_default=False,
        ),
    ]
