# Generated by Django 4.2.14 on 2024-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_loanapplication_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('FIRST_YEAR', 'First Year'), ('SECOND_YEAR', 'Second Year'), ('THIRD_YEAR', 'Third Year'), ('FOURTH_YEAR', 'Fourth Year'), ('FIFTH_YEAR', 'Fifth Year')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='home_county',
            field=models.CharField(choices=[('MIGORI', 'Migori'), ('ISIOLO', 'Isiolo'), ('NAIROBI', 'Nairobi'), ('MAKUENI', 'Makueni')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='mean_grade_attained',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-')], max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='residence_county',
            field=models.CharField(choices=[('MIGORI', 'Migori'), ('ISIOLO', 'Isiolo'), ('NAIROBI', 'Nairobi'), ('MAKUENI', 'Makueni')], max_length=100),
        ),
    ]
