# Generated by Django 4.2.14 on 2024-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_loanapplication_year_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='government_support_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='helb_applied_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
