# Generated by Django 4.2.14 on 2024-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactblock',
            name='html_url',
            field=models.CharField(help_text="{% url 'contact' %}", max_length=200),
        ),
    ]
