# Generated by Django 4.2.14 on 2024-09-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_alter_question_slug_alter_questionresponse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponsearticle',
            name='content',
        ),
        migrations.CreateModel(
            name='QuestionResponseArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_response_article_content', to='help.questionresponsearticle')),
            ],
        ),
    ]
