# Generated by Django 4.2.14 on 2024-09-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_remove_questionresponsearticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponsearticle',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='QuestionResponseArticleContent',
        ),
    ]
