# Generated by Django 4.2.14 on 2024-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0009_questionresponsearticle_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponsearticle',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionresponsearticle',
            name='is_helpful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionresponsearticle',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
