# Generated by Django 4.2.14 on 2024-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0011_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='summary',
            field=models.TextField(blank=True, max_length=6000),
        ),
    ]
