# Generated by Django 4.2.14 on 2024-09-18 15:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
