# Generated by Django 4.2.14 on 2024-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculator',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
