# Generated by Django 4.2.14 on 2024-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_glossary_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate_type', models.CharField(choices=[('F', 'Fixed'), ('V', 'Variable')], default='F', max_length=1)),
                ('min_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('max_rate', models.DecimalField(decimal_places=2, default=32.0, max_digits=6)),
            ],
        ),
        migrations.AddConstraint(
            model_name='loaninterestrate',
            constraint=models.CheckConstraint(check=models.Q(('min_rate__gte', 5.0), ('min_rate__lte', 32.0)), name='min_rate_gte_5_and_lte_32'),
        ),
        migrations.AddConstraint(
            model_name='loaninterestrate',
            constraint=models.UniqueConstraint(fields=('interest_rate_type', 'min_rate', 'max_rate'), name='min_max_rate_interest_rate_type_unique'),
        ),
    ]
