# Generated by Django 4.2.14 on 2024-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loaninterestrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninterestrate',
            name='interest_rate_type',
            field=models.CharField(choices=[('F', 'Fixed'), ('V', 'Variable')], default='F', max_length=1, unique=True),
        ),
    ]
